# Generated by Django 4.1 on 2022-11-11 12:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Events',
            fields=[
                ('events_id', models.AutoField(primary_key=True, serialize=False)),
                ('events_name', models.CharField(max_length=50, verbose_name='Events')),
                ('events_file_name', models.CharField(max_length=150, verbose_name='Events file')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('description', models.TextField(verbose_name='Description')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_date'],
            },
        ),
        migrations.CreateModel(
            name='Model2',
            fields=[
                ('model_id', models.AutoField(primary_key=True, serialize=False)),
                ('model_name', models.CharField(max_length=50, verbose_name='Models')),
                ('model_location', models.CharField(max_length=150, verbose_name='location')),
                ('model_file_name', models.CharField(max_length=50, verbose_name='Models file')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('description', models.TextField(verbose_name='Description')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_date'],
            },
        ),
        migrations.CreateModel(
            name='Trends',
            fields=[
                ('trends_id', models.AutoField(primary_key=True, serialize=False)),
                ('trends_name', models.CharField(max_length=50, verbose_name='Trends')),
                ('trends_file_name', models.CharField(max_length=150, verbose_name='Trends file')),
                ('start_date', models.DateTimeField(blank=True, verbose_name='Start_date')),
                ('end_date', models.DateTimeField(blank=True, verbose_name='End_date')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('description', models.TextField(verbose_name='Description')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_date'],
            },
        ),
        migrations.CreateModel(
            name='Scenario',
            fields=[
                ('scenario_id', models.AutoField(primary_key=True, serialize=False)),
                ('scenario_name', models.CharField(max_length=50, verbose_name='Scenario')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('run_date', models.DateTimeField(blank=True, null=True, verbose_name='Run_date')),
                ('start_date', models.DateTimeField(blank=True, verbose_name='Start_date')),
                ('end_date', models.DateTimeField(blank=True, verbose_name='End_date')),
                ('description', models.TextField(verbose_name='Description')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_by', to=settings.AUTH_USER_MODEL)),
                ('events_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='modelsapp.events')),
                ('model_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='modelsapp.model2')),
                ('run_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='Run_by', to=settings.AUTH_USER_MODEL)),
                ('trends_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='modelsapp.trends')),
            ],
            options={
                'ordering': ['-created_date'],
            },
        ),
    ]
